end/porject1/demobook/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^about/$', views.about, name='about'),
    url(r'^deletebook/(\d+)/$', views.deletebook, name='deletebook'),
    url(r'^deletehero/(\d+)/$', views.deletehero, name='deletehero'),
    url(r'^createdbook/(\d+)/$', views.createdbook, name='createdbook'),
    url(r'^etidhero/(\d+)/$', views.etidhero, name="etidhero"),
    url(r'^addbook/$', views.addbook, name="addbook"),
    url(r'^etidbook/(\d+)/$', views.etidbook, name="etidbook"),

]

end/porject1/demobook/demobook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('booktest.urls', namespace='booktest')),
    path('', include('polls.urls', namespace='polls')),

]

# 项目的所有路由地址配置文件
# admin路由哦是django自带的后台管理路由


# 总路由匹配文件 == 项目路由文件 使用include包含应用路由文件

# 硬编码 在html文件中有很多超级链接 其中href属性如果写成聚堆路径 这种就叫硬编码
# 在开发的过程中可能需要反复修改路由 若使用硬编码非常不方便
# 需要解除硬编码
# 1需要给应用一个app_name = "应用名" 下载应用的urls.py中
# 2在项目路由中给应用分流时 在include中  提供命名空间
# 3 在应用中给每一个路由一个名字
# 4 在html中使用时 href = "{% erl '命名空间名:路由name' 如果需要参数 直接写 %}"
# 以前定位路由 靠总路由正则表达+应用路由正则表达式
# 解除硬编码之后 使用 应用命名空间+应用路由名字

end/porject1/demobook/polls/urls.py
from django.conf.urls import url
from . import views

app_name = "polls"
urlpatterns = [
    url(r'^polls/$', views.polls, name="polls"),
    # url(r'^polls/$', views.IndexView.as_view(), name="polls"),

    url(r'^detail1/(\d+)/$', views.detail1, name="detail1"),
    # url(r'^detail1/(\d+)/$', views.Detail1View.as_view(), name="detail1"),
    url(r'^result/(\d+)$', views.result, name="result"),
    # url(r'^result/(\d+)$', views.ResultView.as_view(), name="result"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^regist/$', views.regist, name="regist")
]

end/porject1/demobook/polls/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    telephone = models.CharField(max_length=20, verbose_name="手机号")
    questions = models.ManyToManyField("Vote")


class Vote(models.Model):
    message = models.CharField(max_length=20, verbose_name="投票问题")


class Option(models.Model):
    content = models.CharField(max_length=20, default=0)
    op_verv = models.IntegerField(default=0)
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)

end/porject1/demobook/templates/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
</head>
<body>
    <form action="#" method="post">
        书籍名字: <input type="text" name="booktitle" placeholder="请输入书籍名称">
        <br>
        出版日期：<input type="date" name="bookpub_date" >
        <br>
        价格：<input type="number" name="bookprice" >
        <br>
        <input type="submit" value="提交">
    </form>

</body>
</html>

end/porject1/demobook/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>

    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
<div class="center">
    {% block header %}
        <div>
            {% if request.user and request.user.username != '' %}
                用户名：{{request.user}} <a href="{% url 'polls:logout' %}">退出</a>
            {% else %}
            <a href="{% url 'polls:login' %}">登陆</a><a href="{% url 'polls:regist' %}">注册</a>
            {% endif %}
        </div>
    {% endblock %}

    {% block body %}
        这里是身体
    {% endblock %}

    {% block footer %}
        这里是底部
    {% endblock %}
</div>
</body>
</html>

end/porject1/demobook/templates/createdbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加页面</title>
</head>
<body>
    <form action="#" method="post">
        英雄名字: <input type="text" name="heroname" placeholder="请输入名字">
        <br>
        英雄技能：<input type="text" name="heroconten" placeholder="请输入英雄技能">
        <br>
        英雄性别：<input type="radio" name="sex" value="male" checked>男 <input type="radio" name="sex" value="female" checked>女
        <br>
        <input type="submit" value="提交">
    </form>
</body>
</html>

end/porject1/demobook/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
</head>
<body>
    <h1>这里是详情页</h1>
    <div>
        <ul>
            {% for hero in books.hero_set.all %}
                <li>{{hero.name}}--{{hero.gender}}--{{hero.conten}}--{{hero.book}}
                    <a href="{% url 'booktest:etidhero' hero.id %}">编辑</a>
                    <a href="{% url 'booktest:deletehero' hero.id %}">删除</a></li>
            {% endfor %}
        </ul>
    </div>
    <a href="{% url 'booktest:createdbook' books.id %}">添加英雄</a>
   {# <a href="/">返回列表</a> #}
    <a href="{% url 'booktest:index' %}">返回列表</a>
</body>
</html>

end/porject1/demobook/templates/detail1.html
{% extends 'base.html' %}
{% block body %}
    <h1>投票信息:{{message.message}}</h1>
    <h2>投票选项</h2>
    <div>
        <form action="{% url 'polls:result' message.id %}" method="post">
            {% csrf_token %}
            {% for vote in message.option_set.all %}
                <input type="radio" name="option" value="{{vote.id}}" checked>{{vote.content}}
                <br>
            {% endfor %}
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'polls:polls' %}">返回</a>
    </div>
{% endblock %}

end/porject1/demobook/templates/etidbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑书籍</title>
</head>
<body>
    <form action="#" method="post">
        书籍名字: <input type="text" name="booktitle" value="{{book.title}}">
        <br>
        书籍日期：<input type="date" name="bookpub_date" value="{{book.pub_date}}">
        <br>
        价格：<input type="text" name="bookprice" value="{{book.price}}">
        <br>
        <input type="submit" value="提交">
    </form>
</body>
</html>

end/porject1/demobook/templates/etidhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑英雄</title>
</head>
<body>
    <form action="#" method="post">
        英雄名字: <input type="text" name="heroname" value="{{hero.name}}">
        <br>
        英雄技能：<input type="text" name="heroconten" value="{{hero.conten}}">
        <br>
        {% if hero.gender == 'male' %}
            英雄性别：<input type="radio" name="sex" value="male" checked>男 <input type="radio" name="sex" value="female" >女
        {% else %}
            英雄性别：<input type="radio" name="sex" value="male" >男 <input type="radio" name="sex" value="female" checked>女
        {% endif %}
        <br>
        <input type="submit" value="提交">
    </form>
</body>
</html>

end/porject1/demobook/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>

    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
<div class="center">
    <h1>这里是首页</h1>
    <img src="/static/img/lbj.jpg" alt="">
    <div>
        <ul>
            {% for book in books %}
            <li>
           {# <a href="/detail/{{book.id}}/"><li>{{book.title}}--{{book.price}}--{{book.pub_date}}</li></a> #}
            <a href="{% url 'booktest:detail' book.id %}">
                {{book.title}}--{{book.price}}--{{book.pub_date}}
            </a>
             <a href="{% url 'booktest:etidbook' book.id %}">编辑</a>
            <a href="{% url 'booktest:deletebook' book.id %}">删除</a>
            </li>
            {% endfor %}
            <a href="{% url 'booktest:addbook' %}">添加书籍</a>
        </ul>
    </div>
</div>

</body>
</html>

end/porject1/demobook/templates/index1.html
{% extends 'base.html' %}

{% block body %}
    <h1>投票信息总汇</h1>
        {% for mess in message %}
            <ul>
                <a href="{% url 'polls:detail1' mess.id %}">
                    <li>{{mess.id}}.{{mess.message}}</li>
                </a>

            </ul>
        {% endfor %}
{% endblock %}

end/porject1/demobook/templates/login.html
{% extends 'base.html' %}

{% block body %}
{% comment %}
    <form action="" method="post">
        {% csrf_token %}
       用户名: <input type="text" name="username" required>
        <br>
        用户密码：<input type="text" name="password" required>
        <br>
        <input type="submit">
        <br>
<!--        {{errors}}-->
    </form>
{% endcomment %}
<form action="#" method="post">
    {% csrf_token %}
    {{lf.username.label}}:{{lf.username}}
    <br>
    {{lf.password.label}}:{{lf.password}}
    <br>
    <input type="submit" value="登录">
</form>

{% endblock %}

end/porject1/demobook/templates/regist.html
{% extends 'base.html' %}

{% block body %}

    <form action="" method="post">
        {% csrf_token %}
       用户名: <input type="text" name="username" required>
        <br>
        输入密码：<input type="text" name="password" required>
        <br>
        确认密码：<input type="text" name="password2" required>
        <br>
        <input type="submit" value="注册">
        <br>
        {{errors}}
    </form>
{% comment %}
<form action="#" method="post">
    {% csrf_token %}
    {{rf.username.label}}:{{rf.username}}
    <br>
    {{rf.password.label}}:{{rf.password}}
    <br>
    {{rf.password2.label}}:{{rf.password2}}
    <br>
    <input type="submit" value="注册">
</form>
{% endcomment %}
{% endblock %}

end/porject1/demobook/templates/result.html
{% extends 'base.html' %}
{% block body %}
    <h1>投票信息</h1>
    <h2>当前得票信息</h2>
    <div>
        <ul>
           {% for option in message.option_set.all %}
                <li>
                   {{option.content}} 票数:{{option.op_verv}}
                    <br>
                </li>

        {% endfor %}
        </ul>
        <a href="{% url 'polls:polls' %}">返回</a>
    </div>
{% endblock %}