end/project4/myapp/apps/blogapp/urls.py
from django.conf.urls import url
from . import views
from django.urls import include

app_name = "blogapp"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^detail/(\d+)/$', views.detail, name="detail"),
    url(r'^tags/$', views.tags, name="tags"),
    url(r'^langure/$', views.langure, name="langure"),
]

end/project4/myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    path('', include('blogapp.urls', namespace="blogapp")),
]

end/project4/myapp/apps/blogapp/models.py
from django.db import models
from DjangoUeditor.models import UEditorField


# Create your models here.


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name="标签名")

    def __str__(self):
        return self.name


# 分类
class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name="分类名")

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    title = models.CharField(max_length=20, verbose_name="标题")
    name = models.CharField(max_length=20, verbose_name="作者名")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    body = UEditorField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(max_length=20, verbose_name="评论人")
    url = models.URLField(default="http://www.rcc.com", verbose_name="个人主页")
    email = models.EmailField(default="1326729135@qq.com", verbose_name="邮箱")
    num = models.PositiveIntegerField(default=3214, verbose_name="验证码")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="所属文章")

    def __str__(self):
        return self.name


# 留言
class leave(models.Model):
    name = models.CharField(max_length=20, verbose_name="名字")
    url = models.URLField(default="http://www.rcc.com", verbose_name="个人主页")
    email = models.EmailField(default="1326729135@qq.com", verbose_name="邮箱")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="留言时间")
    body = models.CharField(max_length=100, verbose_name="内容")

    def __str__(self):
        return self.name


class Comment1(models.Model):
    name = models.CharField(max_length=20, verbose_name="评论人")
    url = models.URLField(default="http://www.rcc.com", verbose_name="个人主页")
    email = models.EmailField(default="1326729135@qq.com", verbose_name="邮箱")
    num = models.PositiveIntegerField(default=3214, verbose_name="验证码")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    body = models.CharField(max_length=100, verbose_name="内容")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="所属文章")

    def __str__(self):
        return self.name

end/project4/myapp/apps/blogapp/forms.py
from django import forms

from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment1
        fields = ["name", "url", "email", "num", "body"]
        labels = {
            "name": "名字",
            "url": "网址",
            "email": "邮箱",
            "num": "验证码",
            "body": "评论"
        }
        widgets = {
            "body": forms.Textarea
        }


class LeaveForm(forms.ModelForm):
    class Meta:
        model = leave
        fields = ["name", "url", "email", "body"]
        labels = {
            "name": "名字",
            "url": "网址",
            "email": "邮箱",
            "body": "评论"
        }
        widgets = {
            "body": forms.Textarea
        }

end/project4/myapp/apps/blogapp/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, Page
from .models import *
from .forms import CommentForm, LeaveForm


# Create your views here.


def index(request):
    article = Article.objects.all()

    typepage = request.GET.get("type")
    year = None
    month = None
    category_id = None
    if typepage == "date":
        year = request.GET.get("year")
        month = request.GET.get("month")
        article = Article.objects.filter(create_time__year=year, create_time__month=month).order_by("-create_time")
    elif typepage == "category":
        category_id = request.GET.get("category_id")
        try:
            category = Category.objects.get(id=category_id)
            article = category.article_set.all()
        except Exception as e:
            print(e)
            return HttpResponse("分类不合法")
    elif typepage == "tag":
        tag_id = request.GET.get("tag_id")
        try:
            tag = Tag.objects.get(id=tag_id)
            article = tag.article_set.all()
        except Exception as e:
            print(e)
            return HttpResponse("标签不合法")
    else:
        article = Article.objects.all()

    paginator = Paginator(article, 2)
    num = request.GET.get("pagenum", 1)
    page = paginator.get_page(num)
    return render(request, 'index.html', locals())


def detail(request, detailid):
    if request.method == "GET":
        try:
            articles = Article.objects.get(id=detailid)
            cf = CommentForm()
            return render(request, 'detail.html', locals())
        except Exception as e:
            return HttpResponse("文章不合法")
    elif request.method == "POST":
        cf = CommentForm(request.POST)
        print(cf,"++++++++++++++++")
        if cf.is_valid():
            print(cf,"+++++++++++++")
            comment = cf.save(commit=False)
            comment.article = Article.objects.get(id=detailid)
            print(comment, "+++++++++++++")
            comment.save()
            print(comment, "------------")
            url = reverse("blogapp:detail", args=(detailid,))
            return redirect(to=url)
        else:
            articles = Article.objects.get(id=detailid)
            cf = CommentForm()
            errors = "输入信息有误"
    return render(request, 'detail.html', locals())


def tags(request):
    article = Article.objects.all()
    return render(request, 'tags.html', locals())


def langure(request):
    if request.method == "GET":
        cf = leave.objects.all()
        return render(request, 'langure.html', locals())
    elif request.method == "POST":
        cf = LeaveForm(request.POST)
        if cf.is_valid():
            cf.save()
            url = reverse("blogapp:langure")
            return redirect(to=url)
    return render(request, 'langure.html', locals())

end/project4/myapp/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta http-equiv="Content-Language" content="zh-CN" />
	<meta name="keywords" content="你我网,圈圈说,汉中,汉中圈圈,你我,如是观,心理,感情,youmew" />
	<meta name="description" content="你我网，缘自圈圈说，记载着圈圈的生活过往，只为留住那份曾经的感动；圈圈，又名小尤，前半生执著于感情，命途多舛，故孑然一身。" />
	<title>你我网</title>
	<link rel="stylesheet" rev="stylesheet" href="/static/style/style.css" type="text/css" media="screen" />
    <link rel="shortcut icon" href="/favicon.ico" />
	<script src="/static/style/common.js" type="text/javascript"></script>
	<script src="/static/style/c_html_js_add.js" type="text/javascript"></script>
	<script src="/static/style/custom.js" type="text/javascript"></script>
	<link rel="alternate" type="application/rss+xml" href="style/feed.css" title="你我网 " />
</head>
<body class="multi default">
<div id="divAll">
	<div id="divPage">
	<div id="divMiddle">
		<div id="divTop">
			<h1 id="BlogTitle"><a href="#"><img src="/static/images/LOGO.gif" alt="你我网" onMouseover="shake(this,'onmouseout')" /></a></h1>
			<!-- <h3 id="BlogSubTitle">www.Youmew.com</h3> -->
		</div>
		<div id="divNavBar">
<ul>
<li><a href="{% url 'blogapp:index' %}">首页</a><li><a href="{% url 'blogapp:tags' %}" target="_blank" title="还是以前的圈圈微博！">圈圈说</a></li><li><a href="{% url 'blogapp:langure' %}" title="沟通从这里开始">留言本</a></li>
</ul>
		</div>
<div id="divMain">

	{% block main %}
    {% endblock %}

    {% block table %}
	{% endblock %}
</div>
<div id="divSidebar">
{% block aside %}
{% endblock %}
<dl class="function" id="divLinkage">
    <dt class="function_t">友情链接</dt>
    <dd class="function_c">
    <ul><li><a href="http://www.nszbk.com" target="_blank">逆时针博客</a>　<a href="http://www.mybiketimes.com/" target="_blank">单车岁月</a>　<a href="http://www.lopwon.com/" target="_blank">立云图志</a></li><li><a href="http://qingchun.org/"target="_blank">青春</a>　<a href="http://www.gaohaipeng.com" target="_blank">高海鹏博客</a>　<a href="http://www.ccaipu.com/" target="_blank">程晨爱蒲</a>　</li></li><li><a href="http://lusongsong.com/daohang" rel="external nofollow" target="_blank">博客大全</a>　<a href="http://bestcherish.com/" target="_blank">灰常记忆</a>　<a href="http://www.swdsblog.com" target="_blank">随望淡思</a></li><li><a href="http://www.wangzhijun.com.cn" target="_blank">王志军博客</a>　<a href="http://duonuli.com/" target="_blank">多努力网</a></li><li></li><li><a href="http://www.panoramio.com/user/youmew" target="_blank">谷歌地球相册</a></li><li><a href="#t/post-18.html" target="_blank" title="申请链接"><span style="color:#006000;">交换友情链接</span></a></li></ul>
    </dd>
</dl>
<dl class="function" id="divMisc">
<dt class="function_t">分享到：</dt>
<dd class="function_c">
<ul><li><img src="/static/images/weixin.jpg" height="110" width="110" border="0" alt="你我网微信公众平台" title="微信扫一扫，关注圈圈的最新消息。" /></li><li><!-- Baidu Button BEGIN --><div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a><a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a><a title="分享到百度贴吧" href="#" class="bds_tieba" data-cmd="tieba"></a><a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a></div><script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":["sqq","weixin","qzone","tsina","tieba","douban"],"bdPic":"","bdStyle":"0","bdSize":"16"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script><!-- Baidu Button END --></li><li><a href="#feed.asp" target="_blank"><img src="/static/images/rss.png" height="31" width="88" border="0" alt="订阅本站的 RSS 2.0 新闻聚合" /></a></li></ul>
</dd>
</dl>

</div>
		<div id="divBottom">
          <h3 id="BlogCopyRight">陕ICP备11002139号-1</h3>
			<h4 id="BlogPowerBy">Powered By <a href="http://www.rainbowsoft.org/" title="RainbowSoft Studio Z-Blog" target="_blank">Z-Blog</a>　本站遵循<a rel="license" target="_blank" title="署名-非商业性使用-禁止演绎 3.0 中国大陆许可协议" href="http://creativecommons.org/licenses/by-nc-nd/3.0/cn/"> CC BY-NC-ND 3.0 CN协议 </a>。</h4>
		</div><div class="clear"></div>
	</div><div class="clear"></div>
	</div><div class="clear"></div>
</div>
<!-- dd BEGIN -->
<script language="JavaScript1.2">
var typ=["marginTop","marginLeft"],rangeN=10,timeout=0;
function shake(o,end){
var range=Math.floor(Math.random()*rangeN);
var typN=Math.floor(Math.random()*typ.length);
o["style"][typ[typN]]=""+range+"px";
var shakeTimer=setTimeout(function(){shake(o,end)},timeout);
o[end]=function(){clearTimeout(shakeTimer)};
}
  </script>
<!-- dd END -->
</body>
</html><!-- 16ms -->

end/project4/myapp/templates/base2.html
{% extends 'base.html'%}
{% load myfun %}
{% block aside %}
<dl class="function" id="divSearchPanel">
<dt class="function_t">搜索</dt>
<dd class="function_c">
<div><div style="padding:0.5em 0 0.5em 1em;">
    <form method="get" action="/search/" target="_blank">
        {% csrf_token %}
        <input type="text" name="q" id="edtSearch" size="12" />
        <input type="submit" value="搜索" name="btnPost" id="btnPost" />
    </form>
</div>
</div>
</dd>
</dl>
<dl class="function" id="divTags">
    <dt class="function_t">按标签浏览</dt>
    {% get_tag as tag %}
    <dd class="function_c">
        <ul>
            {% for tags in tag %}
                <li class="tag-name tag-name-size-2"><a href="/?type=tag&tag_id={{tags.id}}">{{tags.name}}</a></li>
            {% endfor %}
        </ul>
    </dd>
</dl>
<dl class="function" id="divComments">
    <dt class="function_t">最新留言</dt>
    <dd class="function_c">
        {% get_leave as leave %}

    <ul>
        {% for le in leave %}
            <li style="text-overflow:ellipsis;"><a href="#">{{le.body}}</a></li>
        {% endfor %}

    </ul>>
    </dd>
</dl>
{% endblock %}

end/project4/myapp/templates/detail.html
{% extends 'base.html' %}
{% load myfun %}
	{% block main %}
		<div class="post single-post cate2 auth1">

				<h4 class="post-date">{{articles.create_time|date:'Y年m月d日 H:i:s'}}</h4>
				<h2 class="post-title">{{articles.name}}​</h2>
				<div class="post-body">
					<p>{{articles.body|safe}}</p>
				</div>
				<h5 class="post-tags">Tags: <span class="tags">
					{% for t in articles.tags.all %}
					<a href="#catalog.asp?tags=%E6%91%84%E5%BD%B1">{{t.name}}</a>
					{% endfor %}
				</span></h5>
				<h6 class="post-footer">
					发布:{{articles.name}} | 分类:{{articles.category.name}} | 评论:{{articles.comment1_set.count}} | 浏览:<span>{{articles.views}}</span>
<!--					<script type="text/javascript"></script>-->
						<br />
					<!-- AD BEGIN -->
					<br />
				<div style="width:660px;" align="center">

				</div>
					<!-- AD END -->
				</h6>

		</div>
<ul class="msg mutuality">
	<li class="tbname">相关文章:</li>
	<li class="msgarticle">
	{% for a in arts %}
		<p><a  href="#post/77.html">{{a.title}}</a>&nbsp;&nbsp;({{a.create_time|date:'Y年m月d日 H:i:s'}})</p>
	{% endfor %}
	</li>
</ul>
<ul  class="msg msghead">
	<li class="tbname">留言列表:</li>
</ul>
<ins style="display:none;" id="AjaxCommentBegin"></ins>

<ul class="msg" id="cmt1475">
	{% for c in articles.comment1_set.all %}
		<li class="msgname"><img class="avatar" src="http://cn.gravatar.com/avatar/e762b2d63651344d2ca3db6bcef8286b?s=40&d=mm" alt="" width="32"/>&nbsp;
		<span class="commentname">
			{{c.name}}
		</span>
		<br/>
		<small>&nbsp;发布于&nbsp;{{c.create_time|date:'Y年m月d日 H:i:s'}}&nbsp;&nbsp;
			<span class="revertcomment"><a href="#comment" onclick="RevertComment('1475')">回复该留言</a></span>
		</small>
	</li>
	<li class="msgarticle">{{c.body}}</li>
	{% endfor %}
</ul>





<div class="post" id="divCommentPost">
	<p class="posttop"><a name="comment">发表留言:</a>
		<small><a rel="nofollow" id="cancel-reply" href="#divCommentPost" style="display:none;">取消回复</a></small></p>


	<form action="#" method="post" id="frmSumbit">
		{% csrf_token %}
			<div class="row">
					<div class="col-md-4">
							<label>{{cf.name.label}}</label>
							{{cf.name}}
					</div>
					<div class="col-md-4">
							<label>{{cf.email.label}}</label>
							{{cf.email}}
					</div>
					<div class="col-md-4">
							<label>{{cf.url.label}}</label>
							{{cf.url}}
					</div>
					<div class="col-md-4">
							<label>{{cf.num.label}}</label>
							{{cf.num}}
					</div>
					<div class="col-md-12">
							<label>{{cf.body.label}}</label>
							{{cf.body}}
							<br>
							<br>
							<button type="submit" class="comment-btn">发表</button>
					</div>
			</div>
	</form>

	<p class="postbottom">◎欢迎参与讨论，请在这里发表您的看法、交流您的观点。</p>
<!--	<script language="JavaScript" type="text/javascript">LoadRememberInfo();</script>-->
</div>
    {% endblock %}

end/project4/myapp/templates/index.html
{% extends 'base2.html'%}

{% block main %}
	{% for article in page %}
	<div class="post multi-post cate4 auth1">
		<h4 class="post-date">{{article.create_time|date:'Y年m月d日 H:i:s'}}</h4>
		<h2 class="post-title"><a href="{% url 'blogapp:detail' article.id %}">{{article.title}}</a></h2>
		<div class="post-body"><p>{{article.body|safe|truncatechars_html:20}}</p></div>
		<h5 class="post-tags">Tags: <span class="tags">
			{% for a in article.tags.all %}
				<a href="#catalog.asp?tags=%E8%A7%89%E6%82%9F">{{a.name}}</a>
			{% endfor %}
			&nbsp;&nbsp;
		</span></h5>
		<h6 class="post-footer">
			发布:{{article.name}} | 分类:{{article.category.name}} | 评论:{{article.comment1_set.count}} | 浏览:<span id="spn77"></span>
			<script type="text/javascript">{{article.views}}</script> | <a href="{% url 'blogapp:detail' article.id %}">阅读全文 > </a>
		</h6>
	</div>

	{% endfor %}
{% endblock %}
{% block table %}
<div class="post pagebar">

	{% if page.has_previous %}
	<a href="/?pagenum={{page.previous_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}"><span class="page first-page">上一页</span></a>
	{% endif %}

	{% for pn in page.paginator.page_range %}
	{% if pn == page.number %}
	<span class="/?pagenum={{pn}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">{{pn}}</span>
	{% else %}
        <a href="/?pagenum={{pn}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}"><span class="page">{{pn}}</span></a>
	{% endif %}
	{% endfor %}


	{% if page.has_next %}
        <a href="/?pagenum={{page.next_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}"><span class="page last-page">下一页</span></a>
	{% endif %}
</div>
{% endblock %}

end/project4/myapp/templates/langure.html
{% extends 'base.html'%}
{% block main %}
<div class="post" id="divCommentPost">
	<p class="posttop"><a name="comment">发表留言:</a>
	<form action="#" method="post" >
		{% csrf_token %}
			<div class="row">
					<div class="col-md-4">
							<label>{{cf.name.label}}</label>
							{{cf.name}}
					</div>
					<div class="col-md-4">
							<label>{{cf.email.label}}</label>
							{{cf.email}}
					</div>
					<div class="col-md-4">
							<label>{{cf.url.label}}</label>
							{{cf.url}}
					</div>
					<div class="col-md-12">
							<label>{{cf.body.label}}</label>
							{{cf.body}}
							<br>
							<br>
							<button type="submit" class="comment-btn">发表</button>
					</div>
			</div>
	</form>

	<p class="postbottom">◎欢迎参与讨论，请在这里发表您的看法、交流您的观点。</p>
<!--	<script language="JavaScript" type="text/javascript">LoadRememberInfo();</script>-->
</div>
{% endblock %}

end/project4/myapp/templates/tags.html
{% extends 'base.html' %}
	{% block main %}
		{% for a in article %}
			<div class="post multi-post cate2 auth1">
				<h4 class="post-date">{{a.create_time|date:'Y年m月d日 H:i:s'}}</h4>
				<h2 class="post-title"><a href="#post/76.html">{{a.title}}</a></h2>
				<div class="post-body">
					<p>{{a.body|safe|truncatechars_html:20}}</p>
				</div>
				<h5 class="post-tags">Tags: <span class="tags">
					{% for t in a.tags.all %}
						<a href="#catalog.asp?tags=%E7%94%9F%E6%B4%BB">{{t.name}}</a>
					{% endfor %}
				</span></h5>
				<h6 class="post-footer">
					发布:{{a.name}} | 分类:{{a.category.name}} | 评论:{a.comment_set.count}} | 浏览:<span>{{a.views}}</span>
					<script type="text/javascript"></script> | <a href="#post/76.html">阅读全文 > </a>
				</h6>
			</div>
		{% endfor %}
    {% endblock %}